valid_extensions = {
    "js", "jsx", "ts", "tsx",
    "py", "ipynb",
    "java",
    "c", "cpp", "h", "hpp",
    "html", "css",
    "go",
    "swift",
    "rs",
    "hs",
    "rb",
    "ex", "exs",
    "scala",
    "kt", "kts",
    "cs",
    "sol",
    "qasm",
    "glsl", "vert", "frag",
    "asm", "s",
    "m", "mm",
    "lua",
    "dart",
    "r",
    "php",
    "pl",
    "tcl",
    "f90", "f95", "f03", "f08",
    "jl",
    "zig",
    "v",
    "vhdl",
    "verilog", "sv",
    "cu"
}

language_build_files = {
    "JavaScript": ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml"],
    "TypeScript": ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "tsconfig.json"],
    "Python": ["requirements.txt", "Pipfile", "Pipfile.lock", "pyproject.toml", "poetry.lock", "setup.py", "setup.cfg"],
    "Java": ["pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "MANIFEST.MF"],
    "C": ["Makefile", "CMakeLists.txt", "configure.ac", "configure.in"],
    "C++": ["Makefile", "CMakeLists.txt", "configure.ac", "configure.in", "vcpkg.json", "conanfile.txt", "conanfile.py"],
    "Go": ["go.mod", "go.sum"],
    "Rust": ["Cargo.toml", "Cargo.lock"],
    "Swift": ["Package.swift", "project.pbxproj"],
    "Kotlin": ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"],
    "Scala": ["build.sbt", "plugins.sbt"],
    "Ruby": ["Gemfile", "Gemfile.lock"],
    "PHP": ["composer.json", "composer.lock"],
    "Perl": ["cpanfile", "Makefile.PL"],
    "Lua": ["rockspec", "lua-modules"],
    "Haskell": ["stack.yaml", "cabal.project", "package.yaml"],
    "Dart": ["pubspec.yaml", "pubspec.lock"],
    "Objective-C": ["Makefile", "project.pbxproj"],
    "C#": ["*.csproj", "*.sln"],
    "Elixir": ["mix.exs", "mix.lock"],
    "Erlang": ["rebar.config", "rebar.lock"],
    "Fortran": ["Makefile", "CMakeLists.txt"],
    "Julia": ["Project.toml", "Manifest.toml"],
    "R": ["DESCRIPTION", "NAMESPACE", "Renviron", "Rprofile"],
    "Zig": ["build.zig"],
    "V": ["v.mod"],
    "Solidity": ["truffle-config.js", "hardhat.config.js"],
    "CUDA": ["Makefile", "CMakeLists.txt", "cuda.config"],
    "Shell": [".bashrc", ".zshrc", ".bash_profile", "Makefile"],
    "Assembly": ["Makefile", "nasm.build"],
}

